#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Cavokator.Resource", IsApplication=true)]

namespace Cavokator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int wx_option = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_appicon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int options_button = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int airport_entry = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int choose_id_textview = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int linearlayout_button_options = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int linearlayout_wx_bottom = 2131230720;
			
			// aapt resource value: 0x7f080007
			public const int linearlayout_wx_metarstafors = 2131230727;
			
			// aapt resource value: 0x7f080013
			public const int spinnerTarget = 2131230739;
			
			// aapt resource value: 0x7f080005
			public const int wx_clear_button = 2131230725;
			
			// aapt resource value: 0x7f080012
			public const int wx_option_closeButton = 2131230738;
			
			// aapt resource value: 0x7f08000e
			public const int wx_option_metarHours_seekbarText = 2131230734;
			
			// aapt resource value: 0x7f080006
			public const int wx_options_button = 2131230726;
			
			// aapt resource value: 0x7f080011
			public const int wx_options_closeRelativeLayout = 2131230737;
			
			// aapt resource value: 0x7f080009
			public const int wx_options_configuration_text = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int wx_options_mainRelativeLayout = 2131230728;
			
			// aapt resource value: 0x7f08000c
			public const int wx_options_metarHours = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int wx_options_metarHours_seekbar = 2131230733;
			
			// aapt resource value: 0x7f08000b
			public const int wx_options_metarORtafor_spinner = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int wx_options_metarORtafor_text = 2131230730;
			
			// aapt resource value: 0x7f080010
			public const int wx_options_saveDataSwitch = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int wx_options_saveDataText = 2131230735;
			
			// aapt resource value: 0x7f080004
			public const int wx_request_button = 2131230724;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int wx_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int wx_options_dialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int wx_options_spinner = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050013
			public const int Ago = 2131034131;
			
			// aapt resource value: 0x7f050003
			public const int Airport_ID_TextView = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int Clear_button = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int Connection_Error = 2131034118;
			
			// aapt resource value: 0x7f050017
			public const int Day = 2131034135;
			
			// aapt resource value: 0x7f050014
			public const int Days = 2131034132;
			
			// aapt resource value: 0x7f050008
			public const int Error_fetching_airport = 2131034120;
			
			// aapt resource value: 0x7f05001a
			public const int Fetching = 2131034138;
			
			// aapt resource value: 0x7f050018
			public const int Hour = 2131034136;
			
			// aapt resource value: 0x7f050015
			public const int Hours = 2131034133;
			
			// aapt resource value: 0x7f050004
			public const int Icao_Or_Iata = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int Internet_Error = 2131034119;
			
			// aapt resource value: 0x7f050011
			public const int Metar_Issued = 2131034129;
			
			// aapt resource value: 0x7f050019
			public const int Minute = 2131034137;
			
			// aapt resource value: 0x7f050016
			public const int Minutes = 2131034134;
			
			// aapt resource value: 0x7f05000b
			public const int Option_ChooseMetarOrTaforText = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int Option_ConfigurationText = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int Option_Hour = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int Option_Hours = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int Option_JustGetLast = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int Option_MetarHoursText = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int Option_SaveDataText = 2131034128;
			
			// aapt resource value: 0x7f050005
			public const int Requesting_METAR_Information = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int Send_button = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int Server_Timeout = 2131034121;
			
			// aapt resource value: 0x7f050012
			public const int Tafor_Issued = 2131034130;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int dialog_animation = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
