#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Cavokator.Resource", IsApplication=true)]

namespace Cavokator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0c0000
			public const int wx_option = 2131492864;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public const int font = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int fontProviderAuthority = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int fontProviderPackage = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int fontProviderQuery = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int fontStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int fontWeight = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f0a0000
			public const int abc_action_bar_embed_tabs = 2131361792;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070003
			public const int notification_action_color_filter = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int notification_icon_bg_color = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int notification_material_background_media_default_color = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int primary_text_default_material_dark = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int ripple_material_light = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int secondary_text_default_material_dark = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int secondary_text_default_material_light = 2131165190;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0b0004
			public const int compat_button_inset_horizontal_material = 2131427332;
			
			// aapt resource value: 0x7f0b0005
			public const int compat_button_inset_vertical_material = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public const int compat_button_padding_horizontal_material = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public const int compat_button_padding_vertical_material = 2131427335;
			
			// aapt resource value: 0x7f0b0008
			public const int compat_control_corner_material = 2131427336;
			
			// aapt resource value: 0x7f0b0009
			public const int notification_action_icon_size = 2131427337;
			
			// aapt resource value: 0x7f0b000a
			public const int notification_action_text_size = 2131427338;
			
			// aapt resource value: 0x7f0b000b
			public const int notification_big_circle_margin = 2131427339;
			
			// aapt resource value: 0x7f0b0001
			public const int notification_content_margin_start = 2131427329;
			
			// aapt resource value: 0x7f0b000c
			public const int notification_large_icon_height = 2131427340;
			
			// aapt resource value: 0x7f0b000d
			public const int notification_large_icon_width = 2131427341;
			
			// aapt resource value: 0x7f0b0002
			public const int notification_main_column_padding_top = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int notification_media_narrow_margin = 2131427331;
			
			// aapt resource value: 0x7f0b000e
			public const int notification_right_icon_size = 2131427342;
			
			// aapt resource value: 0x7f0b0000
			public const int notification_right_side_padding_top = 2131427328;
			
			// aapt resource value: 0x7f0b000f
			public const int notification_small_icon_background_padding = 2131427343;
			
			// aapt resource value: 0x7f0b0010
			public const int notification_small_icon_size_as_large = 2131427344;
			
			// aapt resource value: 0x7f0b0011
			public const int notification_subtext_size = 2131427345;
			
			// aapt resource value: 0x7f0b0012
			public const int notification_top_pad = 2131427346;
			
			// aapt resource value: 0x7f0b0013
			public const int notification_top_pad_large_text = 2131427347;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_appicon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_action_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_low_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_bg_normal_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int notification_icon_background = 2130837512;
			
			// aapt resource value: 0x7f02000c
			public const int notification_template_icon_bg = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int notification_template_icon_low_bg = 2130837517;
			
			// aapt resource value: 0x7f020009
			public const int notification_tile_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int notify_panel_notification_icon_bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int options_button = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050017
			public const int action0 = 2131034135;
			
			// aapt resource value: 0x7f050014
			public const int action_container = 2131034132;
			
			// aapt resource value: 0x7f05001b
			public const int action_divider = 2131034139;
			
			// aapt resource value: 0x7f050015
			public const int action_image = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int action_text = 2131034134;
			
			// aapt resource value: 0x7f050025
			public const int actions = 2131034149;
			
			// aapt resource value: 0x7f05004a
			public const int airport_entry = 2131034186;
			
			// aapt resource value: 0x7f05000f
			public const int async = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int blocking = 2131034128;
			
			// aapt resource value: 0x7f050018
			public const int cancel_action = 2131034136;
			
			// aapt resource value: 0x7f050049
			public const int choose_id_textview = 2131034185;
			
			// aapt resource value: 0x7f050020
			public const int chronometer = 2131034144;
			
			// aapt resource value: 0x7f050027
			public const int end_padder = 2131034151;
			
			// aapt resource value: 0x7f050011
			public const int forever = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int ghost_view = 2131034112;
			
			// aapt resource value: 0x7f050022
			public const int icon = 2131034146;
			
			// aapt resource value: 0x7f050026
			public const int icon_group = 2131034150;
			
			// aapt resource value: 0x7f050021
			public const int info = 2131034145;
			
			// aapt resource value: 0x7f050012
			public const int italic = 2131034130;
			
			// aapt resource value: 0x7f05000a
			public const int line1 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int line3 = 2131034123;
			
			// aapt resource value: 0x7f05004b
			public const int linearlayout_button_options = 2131034187;
			
			// aapt resource value: 0x7f050048
			public const int linearlayout_wx_bottom = 2131034184;
			
			// aapt resource value: 0x7f05004f
			public const int linearlayout_wx_metarstafors = 2131034191;
			
			// aapt resource value: 0x7f05001a
			public const int media_actions = 2131034138;
			
			// aapt resource value: 0x7f050013
			public const int normal = 2131034131;
			
			// aapt resource value: 0x7f050024
			public const int notification_background = 2131034148;
			
			// aapt resource value: 0x7f05001d
			public const int notification_main_column = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int notification_main_column_container = 2131034140;
			
			// aapt resource value: 0x7f050001
			public const int parent_matrix = 2131034113;
			
			// aapt resource value: 0x7f050023
			public const int right_icon = 2131034147;
			
			// aapt resource value: 0x7f05001e
			public const int right_side = 2131034142;
			
			// aapt resource value: 0x7f050002
			public const int save_image_matrix = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int save_non_transition_alpha = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int save_scale_type = 2131034116;
			
			// aapt resource value: 0x7f050037
			public const int spinnerTarget = 2131034167;
			
			// aapt resource value: 0x7f050019
			public const int status_bar_latest_event_content = 2131034137;
			
			// aapt resource value: 0x7f05000c
			public const int text = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int text2 = 2131034125;
			
			// aapt resource value: 0x7f05001f
			public const int time = 2131034143;
			
			// aapt resource value: 0x7f05000e
			public const int title = 2131034126;
			
			// aapt resource value: 0x7f050005
			public const int transition_current_scene = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int transition_layout_save = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int transition_position = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int transition_scene_layoutid_cache = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int transition_transform = 2131034121;
			
			// aapt resource value: 0x7f050047
			public const int weather_fragment_container = 2131034183;
			
			// aapt resource value: 0x7f05004d
			public const int wx_clear_button = 2131034189;
			
			// aapt resource value: 0x7f050036
			public const int wx_option_closeButton = 2131034166;
			
			// aapt resource value: 0x7f05002e
			public const int wx_option_metarHours_seekbarText = 2131034158;
			
			// aapt resource value: 0x7f05004e
			public const int wx_options_button = 2131034190;
			
			// aapt resource value: 0x7f050035
			public const int wx_options_closeRelativeLayout = 2131034165;
			
			// aapt resource value: 0x7f050032
			public const int wx_options_colorWeatherSwitch = 2131034162;
			
			// aapt resource value: 0x7f050031
			public const int wx_options_colorWeatherText = 2131034161;
			
			// aapt resource value: 0x7f050029
			public const int wx_options_configuration_text = 2131034153;
			
			// aapt resource value: 0x7f050034
			public const int wx_options_divideTaforSwitch = 2131034164;
			
			// aapt resource value: 0x7f050033
			public const int wx_options_divideTaforText = 2131034163;
			
			// aapt resource value: 0x7f050028
			public const int wx_options_mainRelativeLayout = 2131034152;
			
			// aapt resource value: 0x7f05002c
			public const int wx_options_metarHours = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int wx_options_metarHours_seekbar = 2131034157;
			
			// aapt resource value: 0x7f05002b
			public const int wx_options_metarORtafor_spinner = 2131034155;
			
			// aapt resource value: 0x7f05002a
			public const int wx_options_metarORtafor_text = 2131034154;
			
			// aapt resource value: 0x7f050030
			public const int wx_options_saveDataSwitch = 2131034160;
			
			// aapt resource value: 0x7f05002f
			public const int wx_options_saveDataText = 2131034159;
			
			// aapt resource value: 0x7f05004c
			public const int wx_request_button = 2131034188;
			
			// aapt resource value: 0x7f050046
			public const int wx_rwycond_closeButton = 2131034182;
			
			// aapt resource value: 0x7f050045
			public const int wx_rwycond_closeRelativeLayout = 2131034181;
			
			// aapt resource value: 0x7f05003d
			public const int wx_rwycond_depositsCode = 2131034173;
			
			// aapt resource value: 0x7f05003e
			public const int wx_rwycond_depositsText = 2131034174;
			
			// aapt resource value: 0x7f050041
			public const int wx_rwycond_depthCode = 2131034177;
			
			// aapt resource value: 0x7f050042
			public const int wx_rwycond_depthText = 2131034178;
			
			// aapt resource value: 0x7f05003f
			public const int wx_rwycond_extentCode = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int wx_rwycond_extentText = 2131034176;
			
			// aapt resource value: 0x7f050043
			public const int wx_rwycond_frictionCode = 2131034179;
			
			// aapt resource value: 0x7f050044
			public const int wx_rwycond_frictionText = 2131034180;
			
			// aapt resource value: 0x7f05003a
			public const int wx_rwycond_main_error = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int wx_rwycond_rwycode = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int wx_rwycond_rwytext = 2131034172;
			
			// aapt resource value: 0x7f050039
			public const int wx_rwycond_title = 2131034169;
			
			// aapt resource value: 0x7f050038
			public const int wx_rwycond_titleRelativeLayout = 2131034168;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int cancel_button_image_alpha = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int status_bar_notification_info_maxnum = 2131230721;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int notification_action = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int notification_action_tombstone = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int notification_media_action = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int notification_media_cancel_action = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int notification_template_big_media = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int notification_template_big_media_custom = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int notification_template_big_media_narrow = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int notification_template_big_media_narrow_custom = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int notification_template_custom_big = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int notification_template_icon_group = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int notification_template_lines_media = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int notification_template_media = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int notification_template_media_custom = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int notification_template_part_chronometer = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int notification_template_part_time = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int wx_options_dialog = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int wx_options_spinner = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int wx_rwycond_dialog = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int wx_weather_main = 2130903058;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f09003e
			public const int Ago = 2131296318;
			
			// aapt resource value: 0x7f09002c
			public const int Airport_ID_TextView = 2131296300;
			
			// aapt resource value: 0x7f090029
			public const int ApplicationName = 2131296297;
			
			// aapt resource value: 0x7f090028
			public const int CLRD = 2131296296;
			
			// aapt resource value: 0x7f09002b
			public const int Clear_button = 2131296299;
			
			// aapt resource value: 0x7f09002f
			public const int Connection_Error = 2131296303;
			
			// aapt resource value: 0x7f090042
			public const int Day = 2131296322;
			
			// aapt resource value: 0x7f09003f
			public const int Days = 2131296319;
			
			// aapt resource value: 0x7f090006
			public const int Deposit0 = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int Deposit1 = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int Deposit2 = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int Deposit3 = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int Deposit4 = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int Deposit5 = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int Deposit6 = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int Deposit7 = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int Deposit8 = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int Deposit9 = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int DepositNO = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int Deposit_Error = 2131296273;
			
			// aapt resource value: 0x7f09001a
			public const int Depth = 2131296282;
			
			// aapt resource value: 0x7f090018
			public const int Depth00 = 2131296280;
			
			// aapt resource value: 0x7f090019
			public const int Depth99 = 2131296281;
			
			// aapt resource value: 0x7f09001b
			public const int DepthMORE = 2131296283;
			
			// aapt resource value: 0x7f09001d
			public const int DepthNO = 2131296285;
			
			// aapt resource value: 0x7f09001c
			public const int Depth_Error = 2131296284;
			
			// aapt resource value: 0x7f090031
			public const int Error_fetching_airport = 2131296305;
			
			// aapt resource value: 0x7f090012
			public const int Extent1 = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int Extent2 = 2131296275;
			
			// aapt resource value: 0x7f090014
			public const int Extent5 = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int Extent9 = 2131296277;
			
			// aapt resource value: 0x7f090016
			public const int ExtentNO = 2131296278;
			
			// aapt resource value: 0x7f090017
			public const int Extent_Error = 2131296279;
			
			// aapt resource value: 0x7f090045
			public const int Fetching = 2131296325;
			
			// aapt resource value: 0x7f090024
			public const int Friction99 = 2131296292;
			
			// aapt resource value: 0x7f09001f
			public const int FrictionBA91 = 2131296287;
			
			// aapt resource value: 0x7f090020
			public const int FrictionBA92 = 2131296288;
			
			// aapt resource value: 0x7f090021
			public const int FrictionBA93 = 2131296289;
			
			// aapt resource value: 0x7f090022
			public const int FrictionBA94 = 2131296290;
			
			// aapt resource value: 0x7f090023
			public const int FrictionBA95 = 2131296291;
			
			// aapt resource value: 0x7f09001e
			public const int FrictionCoefficient = 2131296286;
			
			// aapt resource value: 0x7f090025
			public const int FrictionNO = 2131296293;
			
			// aapt resource value: 0x7f090026
			public const int Friction_Error = 2131296294;
			
			// aapt resource value: 0x7f090043
			public const int Hour = 2131296323;
			
			// aapt resource value: 0x7f090040
			public const int Hours = 2131296320;
			
			// aapt resource value: 0x7f09002d
			public const int Icao_Or_Iata = 2131296301;
			
			// aapt resource value: 0x7f090030
			public const int Internet_Error = 2131296304;
			
			// aapt resource value: 0x7f090001
			public const int Main_Error = 2131296257;
			
			// aapt resource value: 0x7f09003c
			public const int Metar_Issued = 2131296316;
			
			// aapt resource value: 0x7f090044
			public const int Minute = 2131296324;
			
			// aapt resource value: 0x7f090041
			public const int Minutes = 2131296321;
			
			// aapt resource value: 0x7f090034
			public const int Option_ChooseMetarOrTaforText = 2131296308;
			
			// aapt resource value: 0x7f09003a
			public const int Option_ColorWeatherText = 2131296314;
			
			// aapt resource value: 0x7f090033
			public const int Option_ConfigurationText = 2131296307;
			
			// aapt resource value: 0x7f09003b
			public const int Option_DivideTaforText = 2131296315;
			
			// aapt resource value: 0x7f090037
			public const int Option_Hour = 2131296311;
			
			// aapt resource value: 0x7f090038
			public const int Option_Hours = 2131296312;
			
			// aapt resource value: 0x7f090036
			public const int Option_JustGetLast = 2131296310;
			
			// aapt resource value: 0x7f090035
			public const int Option_MetarHoursText = 2131296309;
			
			// aapt resource value: 0x7f090039
			public const int Option_SaveDataText = 2131296313;
			
			// aapt resource value: 0x7f09002e
			public const int Requesting_METAR_Information = 2131296302;
			
			// aapt resource value: 0x7f090003
			public const int Runway_AllRunways = 2131296259;
			
			// aapt resource value: 0x7f090005
			public const int Runway_Error = 2131296261;
			
			// aapt resource value: 0x7f090002
			public const int Runway_Indicator = 2131296258;
			
			// aapt resource value: 0x7f090004
			public const int Runway_ReportRepeated = 2131296260;
			
			// aapt resource value: 0x7f090027
			public const int SNOCLO = 2131296295;
			
			// aapt resource value: 0x7f09002a
			public const int Send_button = 2131296298;
			
			// aapt resource value: 0x7f090032
			public const int Server_Timeout = 2131296306;
			
			// aapt resource value: 0x7f090046
			public const int TaforNotAvailable = 2131296326;
			
			// aapt resource value: 0x7f09003d
			public const int Tafor_Issued = 2131296317;
			
			// aapt resource value: 0x7f090000
			public const int status_bar_notification_info_overflow = 2131296256;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060005
			public const int TextAppearance_Compat_Notification = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int TextAppearance_Compat_Notification_Info = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int TextAppearance_Compat_Notification_Info_Media = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int TextAppearance_Compat_Notification_Line2 = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int TextAppearance_Compat_Notification_Media = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int TextAppearance_Compat_Notification_Time = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int TextAppearance_Compat_Notification_Time_Media = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int TextAppearance_Compat_Notification_Title = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int TextAppearance_Compat_Notification_Title_Media = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int Widget_Compat_NotificationActionContainer = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int Widget_Compat_NotificationActionText = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int dialog_animation = 2131099660;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
